version: "1"
services:
  - type: web
    name: app-360
    env: node
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: cd artifacts/api-server && pnpm run start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_17YnmtECOwdJ@ep-billowing-snow-am24xzwl-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: PORT
        value: 10000
